changecom(`@@')dnl
#ifndef INCLUDE_RESTCLIENT_CPP_VERSION_H_
#define INCLUDE_RESTCLIENT_CPP_VERSION_H_
#define RESTCLIENT_VERSION "M4_RESTCLIENT_VERSION"
#endif  // INCLUDE_RESTCLIENT_CPP_VERSION_H_
changecom(`#')dnl
